### ISSUE TITLE
Add query to get recent project update media urls by tag and type

### ISSUE THREAD

**Issue by Skunkmeister** [DevLUp-Inc/Feedback#31]
![image](https://user-images.githubusercontent.com/4400062/176062543-d9eb081d-fe59-4ff3-a778-b0c8f0003e2b.png)

**Comment by Skunkmeister** [comment]
from @Exanite: "Also, if you do need to access them from the GdaApi at a later date (e.g., for a refresh button since SSR/SSG only runs on page load), since the service methods are already implemented, adding an endpoint is only 1 step away. "

**Comment by Exanite** [comment]
This is done right?

**Comment by ModeratelyGreek** [comment]
I didn't want to close it because it hasn't been moved to our API yet for validation and more.

This is something I wanted to talk about with you - I'm unsure if it would be appropriate given not only the very specific nature of the query, but also some of the optimizations within (I bundled like 3 queries into one using [$facet](https://www.mongodb.com/docs/manual/reference/operator/aggregation/facet/))

It's probably better to split it up into 3 separate mongodb queries such that usability > efficiency, but idk what best practice is.

**Comment by Exanite** [comment]
The api query that would be implemented in this issue might be able to provide similar functionality:
https://github.com/DevLUp-Inc/Feedback/issues/71

**Comment by ModeratelyGreek** [comment]
It would. It would be unlikely that we could bundle queries together effectively, unless we're assembling aggregation pipelines and then feeding them into a $facet. I could work on that though, it would be a significant optimization. Not a priority...

**Comment by Exanite** [comment]
Splitting the queries is also fine.

It's not going to take too long to begin with and we can further optimize by parallelizing requests and using static generation to cache the generated page.

I'd say that as we continue to work on the site, the query you wrote for the home page will naturally get split into smaller queries, provided that we are aware that we are potentially duplicating code. I prefer to deduplicate code instead of splitting things up unnecessarily.

**Comment by Exanite** [comment]
Also keep in mind that static generation will serve the old page while generating the new version.
This essentially hides any performance cost of SSG.

**Comment by Exanite** [comment]
Closing in favor of https://github.com/DevLUp-Inc/Feedback/issues/31 due to this issue being part of a milestone and the functionality already being implemented
